### ISSUE TITLE
add Dijkstra's Algorithm in c++

### ISSUE THREAD

**Issue by Ankitmohanty2** [trishan9/HelloWorld#162]
i want to work on this issue will u please add the label of hacktoberfest2024

**Comment by trishan9** [comment]
Assigned to you @Ankitmohanty2

**Comment by trishan9** [comment]
Happy contribution!

**Comment by Ankitmohanty2** [comment]
done contribution thank you

**Comment by Ankitmohanty2** [comment]
close the issue thank you

**Comment by trishan9** [comment]
Thanks for your contribution!

**Comment by trishan9** [comment]
Closing the issue as it is resolved already!
