### ISSUE TITLE
write hello world in crystal

### ISSUE THREAD

**Issue by Rudra-choudhary** [trishan9/HelloWorld#224]
i am working on it please add hacktoberfest tag on it and assign this to me

**Comment by Rudra-choudhary** [comment]
hey @trishan9 i have made a PR #225 can u plzz review it and merge

**Comment by trishan9** [comment]
> hey @trishan9 i have made a PR #225 can u plzz review it and merge

Sure!

**Comment by trishan9** [comment]
Your PR has been merged under Hacktoberfest @Rudra-choudhary

**Comment by trishan9** [comment]
Happy contribution!
