### ISSUE TITLE
Adding Java Programs

### ISSUE THREAD

**Issue by ARCHITABHATTAD** [trishan9/HelloWorld#27]
Adding Bubble Sort and Selection Sort in Java

@trishan9 please assign me this issue under hacktoberfest 2023

**Comment by trishan9** [comment]
Ok I will assign you this task

**Comment by trishan9** [comment]
Issue is now assigned to you, you can start working on it @ARCHITABHATTAD

**Comment by trishan9** [comment]
#happycontribution

**Comment by asharavesh** [comment]
@trishan9 can u assign me this task under the hacktoberfest 2023 label

**Comment by trishan9** [comment]
Ok @asharavesh

**Comment by trishan9** [comment]
Assigned to you @asharavesh

**Comment by trishan9** [comment]
Happy Contribution

**Comment by trishan9** [comment]
Ok @aditya-mistri , what would you add can you please be more specific

**Comment by trishan9** [comment]
Issue has been assigned to you @aditya-mistri

**Comment by trishan9** [comment]
Happy Contribution

**Comment by Deepak492001** [comment]
please assign this issue to me.

**Comment by trishan9** [comment]
Issue has been assigned to you! @Deepak492001

**Comment by trishan9** [comment]
Happy contribution

**Comment by ishika1880** [comment]
Please assign this issue to me 
I'll add some medium to Hard Level problems of binary search with a solution

**Comment by trishan9** [comment]
> Please assign this issue to me 
> I'll add some medium to Hard Level problems of binary search with a solution

Ok, make sure to create single PR for each of the program

**Comment by Deepikakolli4** [comment]
Hey @trishan9 ,Can you please assign it to me under hacktoberfest2024 label.

**Comment by trishan9** [comment]
I've assigned you as well! @Deepikakolli4

**Comment by trishan9** [comment]
Happy contribution!

**Comment by Deepikakolli4** [comment]
Hey @trishan9 
I have raised below PR (#123 ) to add linked lists programs

**Comment by trishan9** [comment]
Thanks for the contribution, PR will be reviewed and merged soon! @Deepikakolli4
